aws_access_key_id: "845c339e-9a86-4f72-964c-2613b10902d8"
aws_secret_access_key: "464492933b7a5e08b75c56bb3f99d3e43b52148e598a776d6e89e9139763e243"
endpoint_url: "http://cloud.messner.click:8000"
bucket_name: "webstorage-google-photos"
scopes: 
    - "https://www.googleapis.com/auth/photoslibrary.readonly"
token_file: "photoslibrary.pickle"
secrets_file: "credentials.json"
# local directory to store metadata
tmp_file: "tmp.dmp"
data_dir: "photos"
 
