version: "2.4"

volumes:
    temp_data:

services:
    fotos-sync:
        image: gunny26/docker-google-fotos-sync:2021-10-19
        build: ./
        container_name: fotos-sync
        environment:
            AWS_ACCESS_KEY_ID: "845c339e-9a86-4f72-964c-2613b10902d8"  # s3 id
            AWS_SECRET_ACCESS_KEY: "464492933b7a5e08b75c56bb3f99d3e43b52148e598a776d6e89e9139763e243"  # s3 secret
            ENDPOINT_URL: "http://cloud.messner.click:8000"  # s3 endpoint url
            BUCKET_NAME: "webstorage-google-photos"   # s3 bucket to store data in
            SCOPES: "https://www.googleapis.com/auth/photoslibrary.readonly"  # for photos-api necessary
            TOKEN_FILE: "photoslibrary.pickle"  # stored token
            SECRETS_FILE: "credentials.json"  # google credentials 
            TMP_FILENAME: "/usr/src/app/data/tmp.dmp"  # temporary filename
            INTERVAL: 86400  # one day
            LOG_LEVEL: "INFO"  # used with logging
        volumes:
            - temp_data:/usr/src/app/data  # scratch data
            - ./webstorage.yml:/usr/src/app/.webstorage/webstorage.yml:ro  # webstorage config
            - ./credentials.json:/usr/src/app/data/credentials.json:ro  # google secrets to get a token
            - ./photoslibrary.pickle:/usr/src/app/photoslibrary.pickle:rw  # stored google token
