version: "2.4"

volumes:
    temp_data:

services:
    fotos-sync:
        image: gunny26/docker-google-fotos-sync:2021-10-19
        build: ./
        container_name: fotos-sync
        volumes:
            - temp_data:/usr/src/app/data  # scratch data
            - ./secret/webstorage.yml:/usr/src/app/.webstorage/webstorage.yml:ro  # webstorage config
            - ./secret/credentials.json:/usr/src/app/credentials.json:ro  # google secrets to get a token
            - ./secret/photoslibrary.pickle:/usr/src/app/photoslibrary.pickle:rw  # stored google token
