services:
    fotos-sync:
        image: ghcr.io/gunny26/docker-google-fotos-sync:latest
        container_name: fotos-sync
        environment:
            APP_AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            APP_AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            APP_ENDPOINT_URL: ${ENDPOINT_URL}
            APP_BUCKET_NAME: webstorage-google-photos
            APP_SCOPES: https://www.googleapis.com/auth/photoslibrary.readonly
            APP_TOKEN_FILE: photoslibrary.pickle
            APP_SECRETS_FILE: credentials.json
            APP_TMP_FILENAME: /usr/src/app/data/tmp.dmp
            APP_INTERVAL: 86400
            APP_LOG_LEVEL: INFO
        ports:
            - 9102:9100/tcp
